# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Reads and Quotes
logo:               # Logo image URL
email:              ''
description:        Selection of Quotes & Excerpts
baseurl:            '/readsandquotes' # The subpath of your site, e.g. /blog
url:                'https://github.com/Readers-Blog' # The base hostname & protocol for your site
github_username:    aspirethemes
twitter_username:   ''
instagram_username: ''

markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:             Ginger CauliflowerBread
    bio:              Reading enthusiast and aspiring Minimalist. I love discovering new writings & phylosophies and grow through them.
    gravatar:         ''
    email:            ''
    website:          ''
    github_username:  ''
    twitter_username: ''