# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Reads and Quotes
logo:               # Logo image URL
email:              ''
description:        Selection of Quotes & Excerpts
baseurl:            '/readsandquotes' # The subpath of your site, e.g. /blog
url:                'https://readers-blog.github.io' # The base hostname & protocol for your site
github_username:    ''
twitter_username:   ''
instagram_username: ''

markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Ginger:
    name:             Ginger CauliflowerBread
    bio:              Reading enthusiast and aspiring Minimalist. I love discovering and growing through new readings & phylosophies.
    # gravatar:         ''
    # email:            ''
    website:          https://readers-blog.github.io/readsandquotes/
    # github_username:  ''
    # twitter_username: ''

  Richard Rohr:
    name:             Richard Rohr
    bio:              Richard Rohr is an American author, spiritual writer and Franciscan friar based in Albuquerque, New Mexico. He was ordained to the priesthood in the Roman Catholic Church in 1970.
    gravatar:         https://www.kolbetimes.com/wp-content/uploads/2019/06/Richard-with-his-new-book-300x300.png

    
  Kathleen Dowling Singh:
    name:             Kathleen Dowling Singh
    bio:              Kathleen Dowling Singh is trained academically in transpersonal psychology and works as a mentor for deep psychospiritual growth work. She lectures widely throughout the United States on spirituality at the end of life, spiritual transformation in the midst of life, and meditative and contemplative practices.
    gravatar:         http://www.intheeveningoflife.org/wp-content/uploads/2019/05/Kathleen-Dowling-Singh3.jpg

  Meister Eckhart von Hochheim:
    name:             Meister Eckhart von Hochheim
    bio:              Eckhart von Hochheim, better known to the world as Meister Eckhart, is a German theologian, preacher, mystic, writer, able orator and a renowned philosopher of the XIIIth-XIVth century. His works, ideas and contributions have kindled and captivated the curiosity of the modern readers. He is lauded for his theistic works and his unusual views on God that is grounded on his principle conviction. He was endowed with the honorific title of “meister” (master in German) after he obtained the academic title of ‘Magister in Theologia’ from the University of Paris.
    gravatar:         https://www.thefamouspeople.com/profiles/thumbs/meister-eckhart-4.jpg

  Ernest Becker:
    name:             Ernest Becker
    bio:              Ernest Becker was an American cultural anthropologist and author of the 1974 Pulitzer Prize-winning book, The Denial of Death.
    gravatar:         https://ernestbecker.org/wp-content/uploads/2020/05/becker-1.jpg
  
  Thomas Merton:
    name:             Thomas Merton
    bio:              Thomas Merton was one of the most influential Catholic authors of the 20th century. A Trappist monk of the Abbey of Our Lady of Gethsemani, in the American state of Kentucky, Merton was an acclaimed Catholic spiritual writer, poet, author and social activist. Merton was also a proponent of inter-religious dialogue, engaging in spiritual dialogues with the Dalai Lama, Thich Nhat Hanh and D. T. Suzuki.
    gravatar:         https://scontent-dub4-1.xx.fbcdn.net/v/t31.0-1/p720x720/30171238_1979808722236937_8051619602545111925_o.jpg?_nc_cat=100&ccb=2&_nc_sid=dbb9e7&_nc_ohc=4cS1KPBELDUAX8AMlHq&_nc_ht=scontent-dub4-1.xx&tp=6&oh=8188700ebd48e9e73400e11208022fa1&oe=5FDA4844

    