# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Reads and Quotes
logo:               # Logo image URL
email:              ''
description:        Selection of Quotes & Excerpts
baseurl:            '/readsandquotes' # The subpath of your site, e.g. /blog
url:                'https://readers-blog.github.io' # The base hostname & protocol for your site
github_username:    ''
twitter_username:   ''
instagram_username: ''

markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Ginger:
    name:             Ginger CauliflowerBread
    bio:              Reading enthusiast and aspiring Minimalist. I love discovering new writings & phylosophies and grow through them.
    gravatar:         ''
    email:            ''
    website:          ''
    github_username:  ''
    twitter_username: ''

  Richard Rohr:
    name:             Richard Rohr
    bio:              Richard Rohr is an American author, spiritual writer and Franciscan friar based in Albuquerque, New Mexico. He was ordained to the priesthood in the Roman Catholic Church in 1970.
    gravatar:         https://www.kolbetimes.com/wp-content/uploads/2019/06/Richard-with-his-new-book-300x300.png

    
  Kathleen Dowling Singh:
    name:             Kathleen Dowling Singh
    bio:              Kathleen Dowling Singh is trained academically in transpersonal psychology and works as a mentor for deep psychospiritual growth work. She lectures widely throughout the United States on spirituality at the end of life, spiritual transformation in the midst of life, and meditative and contemplative practices.
    gravatar:         http://www.intheeveningoflife.org/wp-content/uploads/2019/05/Kathleen-Dowling-Singh3.jpg
